output "cluster_name" {
  description = "Name of the AKS cluster"
  value       = azurerm_kubernetes_cluster.main.name
}

output "cluster_endpoint" {
  description = "Endpoint for AKS control plane"
  value       = azurerm_kubernetes_cluster.main.kube_config.0.host
}

output "cluster_ca_certificate" {
  description = "Cluster CA certificate"
  value       = azurerm_kubernetes_cluster.main.kube_config.0.cluster_ca_certificate
}

output "resource_group_name" {
  description = "Name of the resource group"
  value       = azurerm_resource_group.main.name
}

output "vnet_name" {
  description = "Name of the virtual network"
  value       = azurerm_virtual_network.main.name
}

output "subnet_name" {
  description = "Name of the subnet"
  value       = azurerm_subnet.internal.name
}

output "log_analytics_workspace_id" {
  description = "ID of the Log Analytics workspace"
  value       = azurerm_log_analytics_workspace.main.id
}

output "client_certificate" {
  description = "Client certificate for cluster access"
  value       = azurerm_kubernetes_cluster.main.kube_config.0.client_certificate
  sensitive   = true
}

output "client_key" {
  description = "Client key for cluster access"
  value       = azurerm_kubernetes_cluster.main.kube_config.0.client_key
  sensitive   = true
}

output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value = templatefile("${path.module}/kubeconfig.tpl", {
    cluster_name          = azurerm_kubernetes_cluster.main.name
    cluster_endpoint      = azurerm_kubernetes_cluster.main.kube_config.0.host
    cluster_ca_data       = azurerm_kubernetes_cluster.main.kube_config.0.cluster_ca_certificate
    client_certificate    = azurerm_kubernetes_cluster.main.kube_config.0.client_certificate
    client_key           = azurerm_kubernetes_cluster.main.kube_config.0.client_key
    resource_group_name  = azurerm_resource_group.main.name
  })
  sensitive = true
}