output "cluster_name" {
  description = "Name of the GKE cluster"
  value       = google_container_cluster.primary.name
}

output "cluster_endpoint" {
  description = "Endpoint for GKE control plane"
  value       = google_container_cluster.primary.endpoint
}

output "cluster_ca_certificate" {
  description = "Cluster CA certificate"
  value       = google_container_cluster.primary.master_auth.0.cluster_ca_certificate
}

output "cluster_location" {
  description = "Location of the GKE cluster"
  value       = google_container_cluster.primary.location
}

output "network_name" {
  description = "Name of the VPC network"
  value       = google_compute_network.vpc.name
}

output "subnet_name" {
  description = "Name of the subnet"
  value       = google_compute_subnetwork.subnet.name
}

output "service_account_email" {
  description = "Email of the service account"
  value       = google_service_account.kubernetes.email
}

output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value = templatefile("${path.module}/kubeconfig.tpl", {
    cluster_name     = google_container_cluster.primary.name
    cluster_endpoint = google_container_cluster.primary.endpoint
    cluster_ca_data  = google_container_cluster.primary.master_auth.0.cluster_ca_certificate
    project_id       = var.gcp_project_id
    region           = var.gcp_region
  })
  sensitive = true
}