output "cluster_name" {
  description = "Name of the EKS cluster"
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
}

output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

output "ml_artifacts_bucket" {
  description = "S3 bucket for ML artifacts"
  value       = aws_s3_bucket.ml_artifacts.bucket
}

output "datasets_bucket" {
  description = "S3 bucket for datasets"
  value       = aws_s3_bucket.datasets.bucket
}

output "efs_file_system_id" {
  description = "EFS file system ID"
  value       = aws_efs_file_system.ml_shared_storage.id
}

output "efs_file_system_dns_name" {
  description = "EFS file system DNS name"
  value       = aws_efs_file_system.ml_shared_storage.dns_name
}

output "mlflow_db_endpoint" {
  description = "MLflow database endpoint"
  value       = aws_db_instance.mlflow.endpoint
}

output "mlflow_db_port" {
  description = "MLflow database port"
  value       = aws_db_instance.mlflow.port
}

output "node_groups" {
  description = "EKS node groups"
  value = {
    training = module.eks.eks_managed_node_groups["training"]
    gpu_training = module.eks.eks_managed_node_groups["gpu_training"]
    general = module.eks.eks_managed_node_groups["general"]
  }
}

output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value = templatefile("${path.module}/kubeconfig.tpl", {
    cluster_name        = module.eks.cluster_name
    cluster_endpoint    = module.eks.cluster_endpoint
    cluster_ca_data     = module.eks.cluster_certificate_authority_data
    aws_region          = var.aws_region
  })
  sensitive = true
}